## 概念

1. `async` 函数

执行函数，返回值是一个状态为 `fuifilled` 的 `Promise` 对象，对象的结果由 `async` 函数执行的返回值 `return` 值决定，没有 `return` 返回 `undefined`

2. `await` 表达式

`await` 右侧的表达式一般为 `promise` 对象，但也可以是其他值

如果表达式是 `promise` 对象，`await` 返回的是 `promise` 成功的值

如果表达式是其他值，直接将此值作为 `await` 的返回值

3. 注意

`async / await` 作用是用同步方式，执行异步操作

`await` 必须写在 `async` 函数中，但 `async` 函数中可以没有 `await`

如果 `await` 的 `promise` 失败了，就会抛出异常，需要通过 `try...catch` 来捕获处理

## `async` 地狱

`async` 地狱主要是指开发者贪图语法上的简洁而让原本可以并行执行的内容变成了顺序执行。

解决方案：

- `await` 之后跟异步结果

- `Promise.all([handleList(), handleAnotherList()]).then()`

例子一

```javaScript
// async 地狱例子一
(async () => {
  const getList = await getList();
  const getAnotherList = await getAnotherList();
})();

// 修改方案一
(async () => {
  const listPromise = getList();
  const anotherListPromise = getAnotherList();
  await listPromise;
  await anotherListPromise;
})();

// 修改方案二
(async () => {
  Promise.all([getList(), getAnotherList()]).then(...);
})();
```

例子二

```javaScript
(async () => {
  const listPromise = await getList();
  const anotherListPromise = await getAnotherList();

  // do something

  await submit(listData);
  await submit(anotherListData);

})();
```

因为 `await` 的特性，整个例子有明显的先后顺序，然而 `getList()` 和 `getAnotherList()` 其实并无依赖，`submit(listData)` 和 `submit(anotherListData)` 也没有依赖关系，那么对于这种例子，分为三个步骤来改写：

1. 找出依赖关系

在这里，`submit(listData)` 需要在 `getList()` 之后，`submit(anotherListData)` 需要在 `anotherListPromise()` 之后。

2. 将互相依赖的语句包裹在 `async` 函数中

3. 3.并发执行 `async` 函数

```javaScript
async function handleList() {
  const listPromise = await getList();
  // ...
  await submit(listData);
}

async function handleAnotherList() {
  const anotherListPromise = await getAnotherList()
  // ...
  await submit(anotherListData)
}

// 方法一
(async () => {
  const handleListPromise = handleList()
  const handleAnotherListPromise = handleAnotherList()
  await handleListPromise
  await handleAnotherListPromise
})()

// 方法二
(async () => {
  Promise.all([handleList(), handleAnotherList()]).then()
})()
```

## 继发与并发

问题：给定一个 URL 数组，如何实现接口的继发和并发？

`async` 继发实现：

```javaScript
// 继发一
async function loadData() {
  var res1 = await fetch(url1);
  var res2 = await fetch(url2);
  var res3 = await fetch(url3);
  return "whew all done";
}

// 继发二
async function loadData(urls) {
  for (const url of urls) {
    const response = await fetch(url);
    console.log(await response.text());
  }
}
```

`async` 并发实现

```javaScript
// 并发一
async function loadData() {
  var res = await Promise.all([fetch(url1), fetch(url2), fetch(url3)]);
  return "whew all done";
}

// 并发二
async function loadData(urls) {
  // 并发读取 url
  const textPromises = urls.map(async url => {
    const response = await fetch(url);
    return response.text();
  });

  // 按次序输出
  for (const textPromise of textPromises) {
    console.log(await textPromise);
  }
}
```

## `async` 错误捕获

捕获多个错误并做不同的处理时，可以给 `await` 后的 `promise` 对象添加 `catch` 函数，为此需要写一个 `helper`:

```javaScript
// to.js
export default function to(promise) {
   return promise.then(data => {
      return [null, data];
   })
   .catch(err => [err]);
}
```

```javaScript

async function asyncTask(cb) {
    try {
       const user = await UserModel.findById(1);
       if(!user) return cb('No user found');
    } catch(e) {
        return cb('Unexpected error occurred');
    }

    try {
       const savedTask = await TaskModel({userId: user.id, name: 'Demo Task'});
    } catch(e) {
        return cb('Error occurred while saving task');
    }

    if(user.notificationsEnabled) {
        try {
            await NotificationService.sendNotification(user.id, 'Task Created');
        } catch(e) {
            return cb('Error while sending notification');
        }
    }

    if(savedTask.assignedUser.id !== user.id) {
        try {
            await NotificationService.sendNotification(savedTask.assignedUser.id, 'Task was created for you');
        } catch(e) {
            return cb('Error while sending notification');
        }
    }

    cb(null, savedTask);
}

/**
 * =========================>
 * 整个错误捕获的代码可以简化为
 * */

import to from './to.js';

async function asyncTask() {
  let err, user, savedTask;

  [err, user] = await to(UserModel.findById(1));
  if(!user) throw new CustomerError('No user found');

  [err, savedTask] = await to(TaskModel({userId: user.id, name: 'Demo Task'}));
  if(err) throw new CustomError('Error occurred while saving task');

  if(user.notificationsEnabled) {
    const [err] = await to(NotificationService.sendNotification(user.id, 'Task Created'));
    if (err) console.error('Just log the error and continue flow');
  }
}
```

## `async` 的一些讨论

1. `async` 会取代 `Generator` 吗？

`Generator` 本来是用作生成器，使用 `Generator` 处理异步请求只是一个比较 hack 的用法，在异步方面，`async` 可以取代 `Generator`，但是 `async` 和 `Generator` 两个语法本身是用来解决不同的问题的。

2. `async` 会取代 `Promise` 吗？

- `async` 函数返回一个 `Promise` 对象

- 面对复杂的异步流程，`Promise` 提供的 `all` 和 `race` 会更加好用

- `Promise` 本身是一个对象，所以可以在代码中任意传递

- `async` 的支持率还很低，即使有 `Babel`，编译后也要增加 1000 行左右。

## `async` 函数的实现原理


[async 函数](https://es6.ruanyifeng.com/#docs/async)

[ES6 系列之我们来聊聊 Async](https://github.com/mqyqingfeng/Blog/issues/100)

[ES6 系列之 Babel 将 Async 编译成了什么样子](https://github.com/mqyqingfeng/Blog/issues/103)

[精读《AsyncAwait 优越之处》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/4.%E7%B2%BE%E8%AF%BB%E3%80%8AAsyncAwait%20%E4%BC%98%E8%B6%8A%E4%B9%8B%E5%A4%84%E3%80%8B.md)

[精读《async await 是把双刃剑》](https://github.com/ascoders/weekly/blob/master/%E5%89%8D%E6%B2%BF%E6%8A%80%E6%9C%AF/55.%E7%B2%BE%E8%AF%BB%E3%80%8Aasync%20await%20%E6%98%AF%E6%8A%8A%E5%8F%8C%E5%88%83%E5%89%91%E3%80%8B.md)
