## `Promise` 是什么

1. 理解

[Promises/A+规范](https://www.ituring.com.cn/article/66566)

抽象表达：`Promise` 是 `JS` 中进行异步编程的新的解决方案。（旧的是什么）

具体表达：
- 从语法上来讲，`Promise` 是一个构造函数
- 从功能上来说，`promise` 对象用来封装一个异步操作并可以获取其结果

2. `promise` 的状态改变

- `pading` => `resolved`
- `pading` => `rejected`

说明：只有这两种状态改变，且一个 `promise` 对象只能改变一次。无论变成成功或者失败，都会有一个结果数据（value / reason）。

3. `promise` 的基本流程

                       |===>成功执行 resolve() ===> promise 对象 resolved 状态 ===> then() 回调 onResolved()            ===
                       |                                                                                                |
new Promise() panding状态 ===> 执行异步回调                                                                        新的 promise 对象
                       |                                                                                                ｜
                       |===>失败执行 reject() ===> promise 对象 rejected 状态  ===> then()/catch() 回调 onRejected()    ===

`Promise` 是一个承诺，只可能是成功、失败、无响应三种情况之一，一旦决策，无法修改结果。

`Promise` 不属于流程控制，但流程控制可以用多个 `Promise` 组合实现，因此它的职责很单一，就是对一个决议的承诺。



4. `promise` 的基本使用

```javascript
const p = new Promise((resolve, reject) => { // 执行器函数 同步回调
  setTimeout(() => {
    const time = new Date();
    if (time % 2 === 0) {
      resolve(`成功的数据，time = ${time}`);
    } else {
      reject(`失败的数据，time = ${time}`)
    }
  }, 1000);
})

p.then(
  value => {
    // onResolved
    console.log(value);
  },
  reason => {
    // onRejected
    console.log(reason);
  }
)
```

## 为什么要用 `Promise`

1. 执行回调函数的方式更加灵活

旧的：必须在启动异步任务之前指定回调函数。
`promise`：启动异步任务 => 返回 `promise` 对象 => 给 `promise` 对象绑定回调函数（甚至可以在异步任务结束后指定）

2. 支持链式调用，可以解决回调地狱问题

什么是回调地狱？回调函数嵌套调用，外部回调函数异步执行的结果是嵌套的回调函数执行的条件
回调函数的缺点：不便于阅读 / 不便于异常处理

解决方案：`promise` 链式调用
终极解决方法：async / await

```javascript
async function request() {
  try {
    const result = await doSomeThing();
    const newResult = await doSomeThingElse(result);
    const finalResult = await doThirdThing(newResult);
    console.log(finalResult);
  } catch(error) {
    failureCallback(error)
  }
}
```

## 如何使用 `Promise`

1. `Promise` 构造函数：`Promise(excutor){}`

- `excutor` 函数：执行器（同步）函数 `(resolve, reject) => {}`
- `resolve` 函数：内部调用成功时调用的函数 `value => {}`
- `reject` 函数：内部调用失败时调用的函数 `reason => {}`

说明：`excutor` 函数会在 `Promise` 内部立即同步回调，异步操作在执行器中执行。

2. `Promise.prototype.then` （同步）方法：`(onResolved, onRejected) => {}`

- `onResolved` （异步）函数：成功的回调函数 `value => {}`
- `onRejected` （异步）函数：失败的回调函数 `reason => {}`

说明：指定用于得到成功 `value` 的成功回调和用于得到失败 `reason` 的失败回调。返回一个新的 `promise`。

3. `Promise.prototype.catch` 方法：`onRejected => {}`

- `onRejected` 函数：失败的回调函数 `reason => {}`

说明：`then` 的语法糖，相当于 `(undefined, onRejected) => {}`。

4. `Promise.resolve` 方法：`value => {}`

`value`：成功的数据或者 `promise` 对象 

说明：返回一个成功/失败的 `promise` 对象 

5. `Promise.reject` 方法：`reason => {}`

`reason`：失败的原因

说明：返回一个失败的 `promise` 对象 

6. `Promise.all` 方法：`promise[] => {}`

`promise[]`： 包含n个 `promise` 的数组

说明：返回一个新的 `promise` 对象，只有所有的 `promise` 都成功了才成功，成功返回 `value[]`。只有有一个失败就直接失败

7. `Promise.race` 方法：`promise[] => {}`

`promise[]`： 包含n个 `promise` 的数组

说明：返回一个新的 `promise` 对象，第一个完成的 `promise` 结果状态就是最终的结果状态，成功返回 `value / reason`。

## `promise` 的几个关键问题

1. 如何改变 `promise` 的状态

- `resolve(value)`： 如果当前是 `panding` 就会变成 `resolved`
- `reject(reason)`： 如果当前是 `panding` 就会变成 `rejected`
- 抛出异常： 如果当前是 `panding` 就会变成 `rejected`

2. 一个 `promise` 指定了多个成功/失败的回调，都会调用吗？
当 `promise` 改变为对应状态时都会调用

```javascript
let p = new Promise((resolve, reject) => {
  // 抛出异常，状态变成 `rejected`，reason 为 抛出的错误
  throe new Error("error") 
})

p.then(
  value => {},
  reason => {console.log("reason", reason)}
)

p.then(
  value => {},
  reason => {console.log("reason2222", reason)}
)
```

3. 改变 `promise` 状态和指定回调函数谁先谁后。

- 都有可能，正常情况下是先指定回调再改变状态，但也可以先改变状态再指定回调。

```javascript
new Promise((resolve, reject) => {
  setTimeOut(() => { // 再改变状态，同时指定数据，异步调用回调函数
    resolve(1)
  }, 1000)
}).then( // 先指定回调
  value => {},
  reason => {}
)
```

- 如何先改变状态再指定回调？
  - 在执行器中直接调用 `resolve() / reject()`
  ```javascript
  new Promise((resolve, reject) => {
    // 先改变状态,同时指定数据
    resolve(1)  
  }).then( // 再指定回调，异步调用回调函数
    value => {},
    reason => {}
  )
  ```
  - 延迟更长时间再调用 `then()`
  ```javascript
  let p =new Promise((resolve, reject) => {
    setTimeOut(() => {
      resolve(1)
    }, 1000)
  })
  
  setTimeOut(() => {
    p.then(
      value => {},
      reason => {}
    )
  }, 1100)  
  ```

- 什么时候才能得到数据？
  - 如果先指定回调，那么当状态改变时，回调函数就会调用，得到数据
  - 如果先改变状态，那么当指定回调时，回调函数就会调用，得到数据

4. `promise.then()` 返回的新的 `promise` 的结果状态是由什么决定的？

- 简单表达：由 `then()` 指定的回调函数执行的结果决定

- 详细表达：
  - 如果抛出异常，新 `promise` 变为 `rejected`， `reason`为抛出的异常
  - 如果返回的是非 `promise` 的任意值。新 `promise` 变为 `resolved`，`value` 为返回的值。
  - 如果返回的是一个新 `promise` ，此 `promise` 的结果就会成为新 `promise` 的结果

5. `promise` 如何串联多个操作任务

- `promise` 的 `then()`返回一个新的 `promise` ，可以看成 `then()` 的链式调用

- 通过 `then()` 的链式调用串联多个同步异步任务。

6. `promise` 异常传/穿透

- 当使用 `promise` 的 `then()` 链式调用时，可以在最后指定失败的回调
- `onReason` 不写默认为 `reason => {throw reason} / reason => Promise.reject(reason)`
- 前面任何操作出现了异常，都会传到最后的失败回调中处理。

7. 中断 `promise` 链

- 当使用 `promise` 的 `then()` 链式调用时，在中间中断，不再调用之后的回调函数
- 方法：在需要中断的回调函数中返回一个状态为 `pendding` 的 `promise` 对象。

```javascript
.then(() => Promise(() => {}))
```

##  `Promise` 的局限性

1. 吃掉错误

Promise 内部的错误不会影响到 Promise 外部的代码，而这种情况就通常称为 “吃掉错误”。

其实这并不是 Promise 独有的局限性，try..catch 也是这样，同样会捕获一个异常并简单的吃掉错误。

而正是因为错误被吃掉，Promise 链中的错误很容易被忽略掉，这也是为什么会一般推荐在 Promise 链的最后添加一个 catch 函数，因为对于一个没有错误处理函数的 Promise 链，任何错误都会在链中被传播下去，直到你注册了错误处理函数。

2. 单一值

Promise 只能有一个完成值或一个拒绝原因，然而在真实使用的时候，往往需要传递多个值，一般做法都是构造一个对象或数组，然后再传递，then 中获得这个值后，又会进行取值赋值的操作，每次封装和解封都无疑让代码变得笨重。

说真的，并没有什么好的方法，建议是使用 ES6 的解构赋值：

```javaScript
Promise.all([Promise.resolve(1), Promise.resolve(2)])
.then(([x, y]) => {
    console.log(x, y);
});
```

3. 无法取消

Promise 一旦新建它就会立即执行，无法中途取消。

4. 无法得知 pending 状态

当处于 pending 状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。
